/* 今晚吃命 — Demo restaurant data.
   Keep this file free of personal Google Maps exports, private reviews, or real
   visit history. Users should import their own data locally through the app. */
window.HOME_LOC = { lat: 25.0478, lng: 121.517, label: '台北車站' };

window.CITIES = ['台北', '新北', '桃園'];

window.CUISINES = [
  { key: 'taiwanese', label: '台式', emoji: '🥘' },
  { key: 'noodle', label: '麵食', emoji: '🍜' },
  { key: 'snack', label: '小吃', emoji: '🍢' },
  { key: 'japanese', label: '日式', emoji: '🍣' },
  { key: 'hotpot', label: '火鍋', emoji: '🍲' },
  { key: 'thai', label: '南洋', emoji: '🌶️' },
  { key: 'western', label: '西式', emoji: '🍔' },
  { key: 'breakfast', label: '早點', emoji: '🥟' },
  { key: 'poultry', label: '雞鴨鵝', emoji: '🦆' },
  { key: 'dessert', label: '冰甜', emoji: '🍧' },
  { key: 'unknown', label: '待分類', emoji: '❔' },
];

window.SEED_RESTAURANTS = [
  {
    id: 'demo-noodle-001',
    name: '命運牛肉麵',
    cuisine: 'noodle',
    price: 2,
    rating: 4.6,
    lat: 25.0466,
    lng: 121.5169,
    city: '台北',
    addr: '台北市中正區示範路 1 號',
    eatCount: 1,
    lastEaten: '2026-05-12',
    dineIn: true,
    tags: ['demo', '暖胃'],
    blurb: 'Demo 資料：適合想吃熱湯麵的夜晚。',
  },
  {
    id: 'demo-bento-002',
    name: '骰子便當',
    cuisine: 'taiwanese',
    price: 1,
    rating: 4.2,
    lat: 25.0502,
    lng: 121.5202,
    city: '台北',
    addr: '台北市中山區示範街 8 號',
    eatCount: 0,
    lastEaten: '',
    dineIn: true,
    tags: ['demo', '快速'],
    blurb: 'Demo 資料：平日午餐的安全牌。',
  },
  {
    id: 'demo-hotpot-003',
    name: '今晚火鍋局',
    cuisine: 'hotpot',
    price: 3,
    rating: 4.8,
    lat: 25.0418,
    lng: 121.5138,
    city: '台北',
    addr: '台北市萬華區示範路 22 號',
    eatCount: 2,
    lastEaten: '2026-04-20',
    dineIn: true,
    tags: ['demo', '聚餐'],
    blurb: 'Demo 資料：適合多人一起丟命運骰。',
  },
  {
    id: 'demo-sushi-004',
    name: '抽卡壽司',
    cuisine: 'japanese',
    price: 2,
    rating: 4.4,
    lat: 25.054,
    lng: 121.5115,
    city: '台北',
    addr: '台北市大同區示範路 16 號',
    eatCount: 0,
    lastEaten: '',
    dineIn: true,
    tags: ['demo', '清爽'],
    blurb: 'Demo 資料：抽到它就走日式路線。',
  },
  {
    id: 'demo-snack-005',
    name: '夜市命運攤',
    cuisine: 'snack',
    price: 1,
    rating: 4.1,
    lat: 25.063,
    lng: 121.5008,
    city: '新北',
    addr: '新北市三重區示範夜市 3 號',
    eatCount: 3,
    lastEaten: '2026-05-01',
    dineIn: false,
    tags: ['demo', '小吃'],
    blurb: 'Demo 資料：不知道吃正餐還點心時的折衷。',
  },
  {
    id: 'demo-unknown-006',
    name: '神祕小店',
    cuisine: 'unknown',
    price: 1,
    rating: 0,
    lat: 25.0365,
    lng: 121.507,
    city: '台北',
    addr: '台北市中正區待分類路 5 號',
    eatCount: 0,
    lastEaten: '',
    dineIn: true,
    tags: ['demo', '待分類'],
    blurb: 'Demo 資料：用來測試待分類流程。',
  },
];
